# Generated by Django 6.0.4 on 2026-06-25 08:26

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "admin"),
                    ("MANAGER", "manager"),
                    ("EMPLOYEE", "employee"),
                ],
                default="EMPLOYEE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="BD"
            ),
        ),
    ]
